### ISSUE TITLE
2.6 checklist

### ISSUE THREAD

**Issue by gi0baro** [emmett-framework/emmett#511]
- [x] `emmett-core` release
- [x] deprecate `emmett-crypto`
- ecosystem dependencies ready for 3.13
  - [x] renoir
  - [x] severus
- [x] update common extensions to use `emmett-core`
- [x] micro release ready
